/**
 * Invoice Email Template
 * Generates HTML email content for invoice notifications
 */

import type { Locale } from "@/components/internationalization"

interface InvoiceEmailProps {
  recipientName: string
  invoiceNumber: string
  dueDate: string
  total: string
  currency: string
  invoiceUrl: string
  companyName: string
  locale: Locale
  message?: string
}

const translations = {
  en: {
    subject: (invoiceNumber: string, companyName: string) =>
      `Invoice #${invoiceNumber} from ${companyName}`,
    greeting: (name: string) => `Dear ${name},`,
    intro: (companyName: string) =>
      `Please find attached your invoice from ${companyName}.`,
    invoiceDetails: "Invoice Details",
    invoiceNumber: "Invoice Number",
    dueDate: "Due Date",
    totalAmount: "Total Amount",
    viewInvoice: "View Invoice",
    customMessage: "Message from sender",
    footer: (companyName: string) =>
      `Thank you for your business with ${companyName}!`,
    autoGenerated: "This email was automatically generated. Please do not reply directly.",
  },
  ar: {
    subject: (invoiceNumber: string, companyName: string) =>
      `فاتورة رقم ${invoiceNumber} من ${companyName}`,
    greeting: (name: string) => `عزيزي/عزيزتي ${name}،`,
    intro: (companyName: string) =>
      `يرجى الاطلاع على فاتورتك المرفقة من ${companyName}.`,
    invoiceDetails: "تفاصيل الفاتورة",
    invoiceNumber: "رقم الفاتورة",
    dueDate: "تاريخ الاستحقاق",
    totalAmount: "المبلغ الإجمالي",
    viewInvoice: "عرض الفاتورة",
    customMessage: "رسالة من المرسل",
    footer: (companyName: string) =>
      `شكراً لتعاملكم مع ${companyName}!`,
    autoGenerated: "هذا البريد تم إنشاؤه تلقائياً. يرجى عدم الرد مباشرة.",
  },
}

export function generateInvoiceEmailHtml(props: InvoiceEmailProps): string {
  const {
    recipientName,
    invoiceNumber,
    dueDate,
    total,
    currency,
    invoiceUrl,
    companyName,
    locale,
    message,
  } = props

  const t = translations[locale]
  const isRtl = locale === "ar"

  return `
<!DOCTYPE html>
<html lang="${locale}" dir="${isRtl ? "rtl" : "ltr"}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${t.subject(invoiceNumber, companyName)}</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      margin: 0;
      padding: 0;
      background-color: #f5f5f5;
      direction: ${isRtl ? "rtl" : "ltr"};
    }
    .container {
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .card {
      background: #ffffff;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #1a365d 0%, #2c5282 100%);
      color: #ffffff;
      padding: 30px;
      text-align: center;
    }
    .header h1 {
      margin: 0;
      font-size: 24px;
      font-weight: 600;
    }
    .content {
      padding: 30px;
    }
    .greeting {
      font-size: 16px;
      margin-bottom: 20px;
    }
    .intro {
      color: #666;
      margin-bottom: 25px;
    }
    .details-box {
      background: #f8fafc;
      border-radius: 6px;
      padding: 20px;
      margin-bottom: 25px;
    }
    .details-title {
      font-size: 14px;
      font-weight: 600;
      color: #1a365d;
      margin-bottom: 15px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .details-row {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      border-bottom: 1px solid #e2e8f0;
    }
    .details-row:last-child {
      border-bottom: none;
    }
    .details-label {
      color: #718096;
      font-size: 14px;
    }
    .details-value {
      font-weight: 600;
      color: #1a365d;
      font-size: 14px;
    }
    .total-row {
      background: #1a365d;
      color: #ffffff;
      margin: -20px;
      margin-top: 15px;
      padding: 15px 20px;
      border-radius: 0 0 6px 6px;
    }
    .total-row .details-label,
    .total-row .details-value {
      color: #ffffff;
      font-size: 16px;
    }
    .message-box {
      background: #fff3cd;
      border: 1px solid #ffc107;
      border-radius: 6px;
      padding: 15px;
      margin-bottom: 25px;
    }
    .message-title {
      font-size: 12px;
      font-weight: 600;
      color: #856404;
      margin-bottom: 8px;
    }
    .message-text {
      color: #856404;
      font-size: 14px;
    }
    .cta-button {
      display: inline-block;
      background: #3182ce;
      color: #ffffff;
      padding: 14px 28px;
      text-decoration: none;
      border-radius: 6px;
      font-weight: 600;
      font-size: 16px;
      text-align: center;
    }
    .cta-button:hover {
      background: #2c5282;
    }
    .cta-container {
      text-align: center;
      margin: 25px 0;
    }
    .footer {
      text-align: center;
      padding: 20px 30px;
      background: #f8fafc;
      border-top: 1px solid #e2e8f0;
    }
    .footer-text {
      color: #718096;
      font-size: 14px;
      margin-bottom: 10px;
    }
    .footer-note {
      color: #a0aec0;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="card">
      <div class="header">
        <h1>${companyName}</h1>
      </div>
      <div class="content">
        <p class="greeting">${t.greeting(recipientName)}</p>
        <p class="intro">${t.intro(companyName)}</p>

        <div class="details-box">
          <div class="details-title">${t.invoiceDetails}</div>
          <div class="details-row">
            <span class="details-label">${t.invoiceNumber}</span>
            <span class="details-value">${invoiceNumber}</span>
          </div>
          <div class="details-row">
            <span class="details-label">${t.dueDate}</span>
            <span class="details-value">${dueDate}</span>
          </div>
          <div class="details-row total-row">
            <span class="details-label">${t.totalAmount}</span>
            <span class="details-value">${currency} ${total}</span>
          </div>
        </div>

        ${message ? `
        <div class="message-box">
          <div class="message-title">${t.customMessage}</div>
          <div class="message-text">${message}</div>
        </div>
        ` : ""}

        <div class="cta-container">
          <a href="${invoiceUrl}" class="cta-button">${t.viewInvoice}</a>
        </div>
      </div>
      <div class="footer">
        <p class="footer-text">${t.footer(companyName)}</p>
        <p class="footer-note">${t.autoGenerated}</p>
      </div>
    </div>
  </div>
</body>
</html>
  `.trim()
}

export function getInvoiceEmailSubject(
  invoiceNumber: string,
  companyName: string,
  locale: Locale
): string {
  return translations[locale].subject(invoiceNumber, companyName)
}
